//CRIA UM ARRAY
let num = [5,8,4]

//ADICIONA O CONTEÚDO 6 NO INDICE 3
num[3] = 6

//ADICIONA O CONTEUDO 7 DEPOIS DO ULTIMO ELEMENTO
num.push(7)

//DESCOBRIR O COMPRIMENTO DO ARRAY
num.length

//COLOCA TODOS OS ELEMENTOS EM ORDEM CRESCENTE
num.sort()
